version:0.1

phases:
  pre_build:
    commands:
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 168252394093.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t quote-genius-app-api  .
      - docker tag quote-genius-app-api:latest 168252394093.dkr.ecr.us-east-1.amazonaws.com/quotegeniusapi:latest
  post_build:
    commands:
      - docker push 168252394093.dkr.ecr.us-east-1.amazonaws.com/quotegeniusapi:latest 
